version: 2.1
orbs:
  node: circleci/node@5.0.2
  codecov: codecov/codecov@1.1.1
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/meetapp-api/node_modules
      - run: npm run test
        environment:
          JWT_EXPIRATION_TIME: 7d
      - codecov/upload:
          file: tests/coverage/*.json
workflows:
  test:
    jobs:
      - test
