pipeline:
  name: meetapp-api
  properties:
    ci:
      codebase:
        connectorRef: Github_OAuth_1689338959138
        build: <+input>
  stages:
    - stage:
        identifier: test
        name: test
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: NPM Install
                  spec:
                    command: npm install
                  type: Run
              - step:
                  identifier: npmtest
                  name: Run Tests
                  spec:
                    command: npm run test
                  type: Run
              - step:
                  type: Run
                  name: Upload Coverage Results
                  identifier: Coverage
                  spec:
                    shell: Sh
                    command: |-
                      curl -Os https://uploader.codecov.io/latest/linux/codecov
                      chmod +x codecov
                      ./codecov
