pipeline:
  name: Build meetapp-api
  identifier: Build_meetapp_api_1689340884107
  projectIdentifier: Meetapp_API
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesHosted
            spec:
              identifier: k8s-hosted-infra
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Sh
                    command: echo "Welcome to Harness CI"
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1689338959138
        repoName: DiegoVictor/meetapp-api
        build: <+input>
